name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir-version: [1.13.x, 1.12.x, 1.11.x, 1.10.x, 1.9.x]
        include:
          - elixir-version: 1.13.x
            otp-version: 25.x
          - elixir-version: 1.13.x
            otp-version: 24.x
          - elixir-version: 1.12.x
            otp-version: 25.x
          - elixir-version: 1.12.x
            otp-version: 24.x
          - elixir-version: 1.11.x
            otp-version: 23.x
          - elixir-version: 1.10.x
            otp-version: 22.x
          - elixir-version: 1.9.x
            otp-version: 21.x
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          elixir-version: ${{ matrix.elixir-version }}
      - name: Install Elixir Dependencies
        run: mix deps.get
      - name: Lint
        run: |
          mix compile --warnings-as-errors --force
          mix credo --strict
      - name: Run Tests
        run: mix test
      - name: Run Hex Publish test
        run: mix hex.publish --dry-run
        env:
          HEX_API_KEY: DRYRUN
